### ISSUE TITLE
Changing database folder not possible

### ISSUE THREAD

**Issue by christianrauch** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#1]
After installing the "openmediavault-plexmediaserver" plugin the database folder can only be stored on disks which already contain the files the NAS is serving. By default, the package provided at https://plex.tv/downloads sets the database folder to `/var/lib/plexmediaserver/`.

The plex service continuously accesses this folder which prevents the spin-down and power saving mode of the harddrives that contain the actual data. The user should have the possibility to set the database path to the default value `/var/lib/plexmediaserver/` to only spin-up disks, when the media files are actually accessed.

**Comment by ryecoaaron** [comment]
We have always avoided putting databases or other data on the system drive.  Plex is especially bad to put on the system drive because the database can fill the OS drive locking you out of the web interface.  If your OS drive is large enough for the database, then just repartition it.  Then you should be able select the new partition to put the database on.
