### ISSUE TITLE
Plex plugin not found

### ISSUE THREAD

**Issue by Squ4nchy** [OpenMediaVault-Plugin-Developers/openmediavault-plexmediaserver#20]
OMV: v4.1.11
OMVextra: openmediavault-omvextrasorg_latest_all4.deb

After installing OMV extras and turning on the Plex repo, each of these followed by a refresh, I am still unable to find the plex plugin in the plugins section.

I ran the following line, which was found in another post.

`# apt-cache policy openmediavault-plexmediaserver`
`N: Unable to locate package openmediavault-plexmediaserver`

**Comment by ryecoaaron** [comment]
While I wouldn't use the plex plugin (use docker), the plugin is definitely in the repo depending on what architecture your system is - https://bintray.com/openmediavault-plugin-developers/arrakis-plex/openmediavault-plexmediaserver

Let me guess... You are using an armel system?


$ sudo apt-cache policy openmediavault-plexmediaserver
openmediavault-plexmediaserver:
  Installed: (none)
  Candidate: 3.8.2
  Version table:
     3.8.2 500
        500 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch/main amd64 Packages
     3.8.1 500
        500 https://dl.bintray.com/openmediavault-plugin-developers/arrakis-plex stretch/main amd64 Packages

**Comment by Squ4nchy** [comment]
I'm on amd64. I have just tried the docker repo also and still no plex plugin to be found.

**Comment by ryecoaaron** [comment]
I didn't say docker repo.  I said use plex in a docker instead of the plugin - https://forum.openmediavault.org/index.php/Thread/19553-OMV-Docker-plugin-media-server-Plex-PlexPy-Ombi-Libresonic-NZBGet-ruTorrent-Sona/

This really is an issue for the forum since it isn't a problem with the plugin.  Your networking or something must be wrong (DNS issue?)  I bet apt-get update would show a problem.
